# Generated by Django 4.2.7 on 2025-06-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_error_log_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error_log',
            old_name='user',
            new_name='user_id',
        ),
    ]
