# Generated by Django 4.2.7 on 2025-06-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_rename_user_error_log_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='form_view',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roles',
            name='report_view',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roles',
            name='workflow_view',
            field=models.IntegerField(default=0),
        ),
    ]
