# Generated by Django 4.2.7 on 2025-04-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_attributemaster_remove_validationmaster_datatype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldvalidation',
            name='datatype',
        ),
    ]
