# Generated by Django 4.2.7 on 2025-04-09 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0004_actiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_action_id', to='Form.formaction'),
        ),
    ]
