# Generated by Django 4.2.7 on 2025-04-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0005_formdata_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiondata',
            name='form',
        ),
    ]
