# Generated by Django 4.2.7 on 2025-04-11 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0006_remove_actiondata_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiondata',
            name='field_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_field_id', to='Form.formactionfield'),
        ),
    ]
