# Generated by Django 4.2.7 on 2025-04-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0007_actiondata_field_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actiondata',
            old_name='field_id',
            new_name='field',
        ),
    ]
