# Generated by Django 4.2.7 on 2025-04-14 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0008_rename_field_id_actiondata_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfile',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_file_id', to='Form.formfield'),
        ),
        migrations.AlterField(
            model_name='formfile',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_id', to='Form.formfieldvalues'),
        ),
        migrations.AlterField(
            model_name='formfile',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_filr_id', to='Form.form'),
        ),
        migrations.AlterField(
            model_name='formfile',
            name='form_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_data_id', to='Form.formdata'),
        ),
    ]
