# Generated by Django 4.2.7 on 2025-04-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0009_alter_formfile_field_alter_formfile_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDropdownData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'master_drodpown_data',
            },
        ),
    ]
