# Generated by Django 4.2.7 on 2025-04-21 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0011_remove_formfieldvalues_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldvalues',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_data', to='Form.form'),
        ),
    ]
