# Generated by Django 4.2.7 on 2025-04-24 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0012_formfieldvalues_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormGenerativeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.TextField(blank=True, null=True)),
                ('field_name', models.TextField(blank=True, null=True)),
                ('increment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_genrative_id', to='Form.form')),
            ],
            options={
                'db_table': 'form_generative_field',
            },
        ),
    ]
