# Generated by Django 4.2.7 on 2025-04-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0014_formgenerativefield_suffix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formgenerativefield',
            name='suffix',
        ),
    ]
