# Generated by Django 4.2.7 on 2025-04-28 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0016_formgenerativefield_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='formgenerativefield',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_genrative_id', to='Form.formfield'),
        ),
    ]
