# Generated by Django 4.2.7 on 2025-04-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0017_formgenerativefield_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formgenerativefield',
            old_name='suffix',
            new_name='no_of_zero',
        ),
    ]
