# Generated by Django 4.2.7 on 2025-04-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0018_rename_suffix_formgenerativefield_no_of_zero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formgenerativefield',
            old_name='field_name',
            new_name='selected_field_id',
        ),
    ]
