# Generated by Django 4.2.7 on 2025-04-29 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0019_rename_field_name_formgenerativefield_selected_field_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldvalues',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_value_id', to='Form.formfield'),
        ),
        migrations.AlterField(
            model_name='formfieldvalues',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_data', to='Form.form'),
        ),
        migrations.AlterField(
            model_name='formfieldvalues',
            name='form_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_value_id', to='Form.formdata'),
        ),
    ]
