# Generated by Django 4.2.7 on 2025-04-29 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0020_alter_formfieldvalues_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldvalues',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_value_id', to='Form.formfield'),
        ),
        migrations.AlterField(
            model_name='formfieldvalues',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_data', to='Form.form'),
        ),
        migrations.AlterField(
            model_name='formfieldvalues',
            name='form_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_value_id', to='Form.formdata'),
        ),
        migrations.AlterField(
            model_name='formfile',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_file_id', to='Form.formfield'),
        ),
        migrations.AlterField(
            model_name='formfile',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_id', to='Form.formfieldvalues'),
        ),
        migrations.AlterField(
            model_name='formfile',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_filr_id', to='Form.form'),
        ),
        migrations.AlterField(
            model_name='formfile',
            name='form_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_data_id', to='Form.formdata'),
        ),
    ]
