# Generated by Django 4.2.7 on 2025-04-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0021_alter_formfieldvalues_field_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControlMaster',
        ),
        migrations.DeleteModel(
            name='ControlSubMaster1',
        ),
        migrations.DeleteModel(
            name='FieldMaster',
        ),
        migrations.DeleteModel(
            name='FormFieldMaster',
        ),
    ]
