# Generated by Django 4.2.7 on 2025-05-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0022_delete_controlmaster_delete_controlsubmaster1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='secondary_field_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formfield',
            name='secondary_form_id',
            field=models.IntegerField(default=0),
        ),
    ]
