# Generated by Django 4.2.7 on 2025-05-02 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0023_formfield_secondary_field_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='secondary_field_id',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='secondary_form_id',
        ),
        migrations.CreateModel(
            name='FieldDropdownSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_field_id', to='Form.formfield')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_form_id', to='Form.form')),
            ],
            options={
                'db_table': 'field_drodpown_selection',
            },
        ),
    ]
