# Generated by Django 4.2.7 on 2025-05-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0024_remove_formfield_secondary_field_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='selected_field_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='selected_form_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
