# Generated by Django 4.2.7 on 2025-05-02 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0025_formfield_selected_field_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='selected_field_id',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='selected_form_id',
        ),
    ]
