# Generated by Django 4.2.7 on 2025-05-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0026_remove_formfield_selected_field_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldDropdownSelection',
        ),
    ]
