# Generated by Django 4.2.7 on 2025-05-05 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0028_formincrementno'),
    ]

    operations = [
        migrations.AddField(
            model_name='formincrementno',
            name='form_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_data_increment_id', to='Form.formdata'),
        ),
    ]
