# Generated by Django 4.2.7 on 2025-05-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0029_formincrementno_form_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formincrementno',
            name='form_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
