# Generated by Django 4.2.7 on 2025-05-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0030_alter_formincrementno_form_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formincrementno',
            name='increment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
