# Generated by Django 4.2.7 on 2025-05-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0031_alter_formincrementno_increment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonmaster',
            name='sub_master1',
        ),
        migrations.RemoveField(
            model_name='commonmaster',
            name='sub_master2',
        ),
    ]
