# Generated by Django 4.2.7 on 2025-05-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0032_remove_commonmaster_sub_master1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='section',
            field=models.TextField(blank=True, null=True),
        ),
    ]
