# Generated by Django 4.2.7 on 2025-05-07 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0034_sectionmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowVersionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(blank=True, null=True)),
                ('version_no', models.TextField(blank=True, null=True)),
                ('baseline_date', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.TextField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('form_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_data_version_id', to='Form.formdata')),
            ],
            options={
                'db_table': 'workflow_version_control',
            },
        ),
    ]
