# Generated by Django 4.2.7 on 2025-05-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0036_alter_workflowversioncontrol_version_no_formfiletemp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldvalues',
            name='is_workflow',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
