# Generated by Django 4.2.7 on 2025-05-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0037_formfieldvalues_is_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfieldvalues',
            name='is_workflow',
        ),
        migrations.AddField(
            model_name='formdata',
            name='is_workflow',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
