# Generated by Django 4.2.7 on 2025-05-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0038_remove_formfieldvalues_is_workflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiondata',
            name='step_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
