# Generated by Django 4.2.7 on 2025-05-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0039_actiondata_step_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='is_workflow',
        ),
    ]
