# Generated by Django 4.2.7 on 2025-05-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0040_remove_formdata_is_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowversioncontrol',
            name='baseline_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
