# Generated by Django 4.2.7 on 2025-05-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0041_alter_workflowversioncontrol_baseline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='file_ref',
            field=models.TextField(blank=True, null=True),
        ),
    ]
