# Generated by Django 4.2.7 on 2025-05-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0043_rename_old_field_id_formfieldvaluestemp_old_field_value_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfiletemp',
            old_name='old_field_id',
            new_name='old_field_value_id',
        ),
    ]
