# Generated by Django 4.2.7 on 2025-05-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0044_rename_old_field_id_formfiletemp_old_field_value_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfiletemp',
            name='field',
        ),
        migrations.RemoveField(
            model_name='formfiletemp',
            name='file',
        ),
        migrations.RemoveField(
            model_name='formfiletemp',
            name='form',
        ),
        migrations.RemoveField(
            model_name='formfiletemp',
            name='form_data',
        ),
        migrations.AddField(
            model_name='formfiletemp',
            name='field_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfiletemp',
            name='file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfiletemp',
            name='form_data_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfiletemp',
            name='form_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfieldvaluestemp',
            name='field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfieldvaluestemp',
            name='form',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfieldvaluestemp',
            name='form_data',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
