# Generated by Django 4.2.7 on 2025-05-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0045_remove_formfiletemp_field_remove_formfiletemp_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfieldvaluestemp',
            old_name='field',
            new_name='field_id',
        ),
        migrations.RenameField(
            model_name='formfieldvaluestemp',
            old_name='form',
            new_name='form_data_id',
        ),
        migrations.RenameField(
            model_name='formfieldvaluestemp',
            old_name='form_data',
            new_name='form_id',
        ),
    ]
