# Generated by Django 4.2.7 on 2025-05-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0046_rename_field_formfieldvaluestemp_field_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfieldvaluestemp',
            old_name='field_id',
            new_name='field',
        ),
        migrations.RenameField(
            model_name='formfieldvaluestemp',
            old_name='form_data_id',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='formfieldvaluestemp',
            old_name='form_id',
            new_name='form_data',
        ),
    ]
