# Generated by Django 4.2.7 on 2025-05-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0047_rename_field_id_formfieldvaluestemp_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldvaluestemp',
            name='old_form_data',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfiletemp',
            name='old_form_data',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
