# Generated by Django 4.2.7 on 2025-05-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0048_formfieldvaluestemp_old_form_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDataTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.IntegerField(blank=True, null=True)),
                ('action', models.IntegerField(blank=True, null=True)),
                ('req_no', models.TextField(blank=True, null=True)),
                ('file_ref', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'form_data_temp',
            },
        ),
    ]
