# Generated by Django 4.2.7 on 2025-05-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0049_formdatatemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowversioncontrol',
            name='file_category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
