# Generated by Django 4.2.7 on 2025-05-14 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0053_rename_field_formfieldvaluestemp_field_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfieldvaluestemp',
            name='old_field_value_id',
        ),
        migrations.RemoveField(
            model_name='formfiletemp',
            name='old_field_value_id',
        ),
    ]
