# Generated by Django 4.2.7 on 2025-05-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0054_remove_formfieldvaluestemp_old_field_value_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowversioncontrol',
            name='modified_by',
        ),
    ]
