# Generated by Django 4.2.7 on 2025-05-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0055_remove_workflowversioncontrol_modified_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowversioncontrol',
            old_name='file_category',
            new_name='modified_by',
        ),
    ]
