# Generated by Django 4.2.7 on 2025-05-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0056_rename_file_category_workflowversioncontrol_modified_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormDataTemp',
        ),
        migrations.RemoveField(
            model_name='formfieldvaluestemp',
            name='old_form_data_id',
        ),
        migrations.RemoveField(
            model_name='formfiletemp',
            name='old_form_data',
        ),
    ]
