# Generated by Django 4.2.7 on 2025-05-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0056_rename_file_category_workflowversioncontrol_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowversioncontrol',
            name='file_category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
