# Generated by Django 4.2.7 on 2025-05-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0057_workflowversioncontrol_file_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowversioncontrol',
            name='approved_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
