# Generated by Django 4.2.7 on 2025-05-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0057_delete_formdatatemp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldvaluestemp',
            name='old_form_data_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfiletemp',
            name='old_form_data',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
