# Generated by Django 4.2.7 on 2025-05-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0058_alter_workflowversioncontrol_approved_by'),
        ('Form', '0058_formfieldvaluestemp_old_form_data_id_and_more'),
    ]

    operations = [
    ]
