# Generated by Django 4.2.7 on 2025-05-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0059_merge_20250516_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldvalues',
            name='file_ref',
            field=models.TextField(blank=True, null=True),
        ),
    ]
