# Generated by Django 4.2.7 on 2025-05-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0061_versioncontrolfilemap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versioncontrolfilemap',
            old_name='form_data_id',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='versioncontrolfilemap',
            old_name='form_id',
            new_name='form_data',
        ),
    ]
