# Generated by Django 4.2.7 on 2025-05-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0062_rename_form_data_id_versioncontrolfilemap_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versioncontrolfilemap',
            name='form',
        ),
    ]
