# Generated by Django 4.2.7 on 2025-05-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0063_remove_versioncontrolfilemap_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowversioncontrol',
            name='baseline_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
