# Generated by Django 4.2.7 on 2025-05-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0063_remove_versioncontrolfilemap_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiondata',
            name='version',
            field=models.TextField(blank=True, null=True),
        ),
    ]
