# Generated by Django 4.2.7 on 2025-05-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0065_alter_workflowversioncontrol_version_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiondata',
            name='version',
        ),
    ]
