# Generated by Django 4.2.7 on 2025-05-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0067_actionversionno_actiondata_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionversionno',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
