# Generated by Django 4.2.7 on 2025-05-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0068_actionversionno_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionVersionNo',
        ),
    ]
