# Generated by Django 4.2.7 on 2025-05-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0069_delete_actionversionno'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowVersionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.IntegerField(blank=True, null=True)),
                ('form_data_id', models.IntegerField(blank=True, null=True)),
                ('prev_version', models.TextField(blank=True, null=True)),
                ('curr_version', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_version_details',
            },
        ),
    ]
