# Generated by Django 4.2.7 on 2025-05-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0070_workflowversiondetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowversiondetails',
            name='status',
        ),
    ]
