# Generated by Django 4.2.7 on 2025-05-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0071_remove_workflowversiondetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowversioncontrol',
            name='version_no',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
