# Generated by Django 4.2.7 on 2025-05-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0072_alter_workflowversioncontrol_version_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowversioncontrol',
            name='temp_version',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
