# Generated by Django 4.2.7 on 2025-05-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0064_alter_workflowversioncontrol_baseline_date'),
        ('Form', '0073_workflowversioncontrol_temp_version'),
    ]

    operations = [
    ]
