# Generated by Django 4.2.7 on 2025-05-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0074_merge_20250523_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_file_id', models.BigIntegerField()),
                ('file_name', models.TextField(blank=True, null=True)),
                ('uploaded_name', models.TextField(blank=True, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('field_id', models.BigIntegerField(blank=True, null=True)),
                ('file_id', models.BigIntegerField(blank=True, null=True)),
                ('form_id', models.BigIntegerField(blank=True, null=True)),
                ('form_data_id', models.BigIntegerField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'form_file_log',
            },
        ),
    ]
