# Generated by Django 4.2.7 on 2025-05-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0075_formfilelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormFileLog',
        ),
    ]
