# Generated by Django 4.2.7 on 2025-05-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0076_delete_formfilelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfieldvaluestemp',
            name='old_form_data_id',
        ),
        migrations.RemoveField(
            model_name='formfiletemp',
            name='old_form_data',
        ),
    ]
