# Generated by Django 4.2.7 on 2025-05-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0077_remove_formfieldvaluestemp_old_form_data_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='versioncontrolfilemap',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
