# Generated by Django 4.2.7 on 2025-06-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0078_versioncontrolfilemap_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiondata',
            name='version',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
