# Generated by Django 4.2.7 on 2025-06-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0080_formdata_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.TextField(blank=True, null=True)),
                ('version', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_version',
            },
        ),
        migrations.DeleteModel(
            name='WorkflowVersionDetails',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='version',
        ),
    ]
