# Generated by Django 4.2.7 on 2025-07-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0081_workflowversion_delete_workflowversiondetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfile',
            name='file_size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfile',
            name='num_pages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
