# Generated by Django 4.2.7 on 2025-07-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0082_formfile_file_size_formfile_num_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfilehist',
            name='file_size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfiletemp',
            name='file_size',
            field=models.TextField(blank=True, null=True),
        ),
    ]
