# Generated by Django 4.2.7 on 2025-07-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0083_formfilehist_file_size_formfiletemp_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfilehist',
            name='num_pages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfiletemp',
            name='num_pages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
