# Generated by Django 4.2.7 on 2025-07-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0084_formfilehist_num_pages_formfiletemp_num_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowversioncontrol',
            name='workflow_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
