# Generated by Django 4.2.7 on 2025-04-15 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_citymaster_statemaster_districtmaster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtmaster',
            name='city',
        ),
        migrations.AddField(
            model_name='citymaster',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts_id', to='Masters.districtmaster'),
        ),
        migrations.AlterField(
            model_name='citymaster',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='Masters.statemaster'),
        ),
        migrations.AlterField(
            model_name='districtmaster',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='Masters.statemaster'),
        ),
    ]
