# Generated by Django 4.2.7 on 2025-05-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0004_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pdf_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
