# Generated by Django 4.2.7 on 2025-05-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0004_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='para_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para_name', models.CharField(max_length=100)),
                ('para_details', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'para_master',
            },
        ),
    ]
