# Generated by Django 4.2.7 on 2025-05-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0005_para_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='para_master',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='para_master',
            name='para_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='para_master',
            name='para_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
