# Generated by Django 4.2.7 on 2025-05-29 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0006_alter_para_master_description_and_more'),
        ('Masters', '0006_document_field_id_document_file_id_and_more'),
    ]

    operations = [
    ]
