# Generated by Django 4.2.7 on 2025-06-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0007_merge_20250529_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='num_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
