# Generated by Django 4.2.7 on 2025-06-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0008_document_file_size_document_num_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='num_pages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
