from django.urls import path

from .views import (
charts_apex_area_view,
charts_apex_bar_view,
charts_apex_bubble_view,
charts_apex_candlestick_view,
charts_apex_column_view,
charts_apex_heatmap_view,
charts_apex_line_view,
charts_apex_mixed_view,
charts_apex_timline_view,
charts_apex_boxplot_view,
charts_apex_treemap_view,
charts_apex_pie_view,
charts_apex_radar_view,
charts_apex_radialbar_view,
charts_apex_scatter_view,
charts_apex_polararea_view,
charts_apex_sparklines_view,
charts_chartjs_area_view,
charts_chartjs_bar_view,
charts_chartjs_line_view,
charts_chartjs_other_view,
charts_brite_view,
charts_sparkline_view,
)

app_name = "charts"
urlpatterns = [
    path("apex/area", view=charts_apex_area_view, name="apex.area"),
    path("apex/bar", view=charts_apex_bar_view, name="apex.bar"),
    path("apex/bubble", view=charts_apex_bubble_view, name="apex.bubble"),
    path("apex/candlestick", view=charts_apex_candlestick_view, name="apex.candlestick"),
    path("apex/column", view=charts_apex_column_view, name="apex.column"),
    path("apex/heatmap", view=charts_apex_heatmap_view, name="apex.heatmap"),
    path("apex/line", view=charts_apex_line_view, name="apex.line"),
    path("apex/mixed", view=charts_apex_mixed_view, name="apex.mixed"),
    path("apex/timeline", view=charts_apex_timline_view, name="apex.timeline"),
    path("apex/boxplot", view=charts_apex_boxplot_view, name="apex.boxplot"),
    path("apex/treemap", view=charts_apex_treemap_view, name="apex.treemap"),
    path("apex/pie", view=charts_apex_pie_view, name="apex.pie"),
    path("apex/radar", view=charts_apex_radar_view, name="apex.radar"),
    path("apex/radialbar", view=charts_apex_radialbar_view, name="apex.radialbar"),
    path("apex/scatter", view=charts_apex_scatter_view, name="apex.scatter"),
    path("apex/polar-area", view=charts_apex_polararea_view, name="apex.polar-area"),
    path("apex/sparklines", view=charts_apex_sparklines_view, name="apex.sparklines"),
    path("chartjs/area", view=charts_chartjs_area_view, name="chartjs.area"),
    path("chartjs/bar", view=charts_chartjs_bar_view, name="chartjs.bar"),
    path("chartjs/line", view=charts_chartjs_line_view, name="chartjs.line"),
    path("chartjs/other", view=charts_chartjs_other_view, name="chartjs.other"),
    path("brite", view=charts_brite_view, name="brite"),
    path("sparkline", view=charts_sparkline_view, name="sparkline"),
   
]
