# Generated by Django 4.2.7 on 2025-04-07 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='workflow_action_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.TextField(blank=True, null=True)),
                ('action_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_action_details',
            },
        ),
        migrations.CreateModel(
            name='workflow_action_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.TextField(blank=True, null=True)),
                ('action_id', models.IntegerField(blank=True, null=True)),
                ('action_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_action_master',
            },
        ),
        migrations.CreateModel(
            name='workflow_document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dispatch_no', models.TextField(blank=True, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_document',
            },
        ),
        migrations.CreateModel(
            name='workflow_matrix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workflow_name', models.TextField(blank=True, null=True)),
                ('form_id', models.IntegerField(blank=True, null=True)),
                ('step_name', models.TextField(blank=True, null=True)),
                ('button_type_id', models.IntegerField(blank=True, null=True)),
                ('button_act_details', models.IntegerField(blank=True, null=True)),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_matrix',
            },
        ),
        migrations.CreateModel(
            name='workflow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dispatch_type', models.TextField(blank=True, null=True)),
                ('dispatch_no', models.TextField(blank=True, null=True)),
                ('received_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('from_field', models.TextField(blank=True, db_column='from', null=True)),
                ('to', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('send_user', models.TextField(blank=True, null=True)),
                ('branch', models.TextField(blank=True, null=True)),
                ('stakeholders', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_wf', to='Masters.status_master')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow',
            },
        ),
    ]
