# Generated by Django 4.2.7 on 2025-04-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_matrix',
            name='role_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
