# Generated by Django 4.2.7 on 2025-04-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0003_workflow_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow_details',
            old_name='action_id',
            new_name='form_data_id',
        ),
        migrations.RenameField(
            model_name='workflow_details',
            old_name='form_id',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='workflow_details',
            name='req_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
