# Generated by Django 4.2.7 on 2025-04-10 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0004_rename_action_id_workflow_details_form_data_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='workflow_details',
        ),
    ]
