# Generated by Django 4.2.7 on 2025-04-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0005_delete_workflow_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='workflow_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workflow_id', models.IntegerField(blank=True, null=True)),
                ('step_id', models.IntegerField(blank=True, null=True)),
                ('form_data_id', models.IntegerField(blank=True, null=True)),
                ('req_id', models.TextField(blank=True, null=True)),
                ('action_details_id', models.IntegerField(blank=True, null=True)),
                ('role_id', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_details',
            },
        ),
    ]
