# Generated by Django 4.2.7 on 2025-04-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0006_workflow_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_matrix',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
