# Generated by Django 4.2.7 on 2025-04-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0007_workflow_matrix_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_matrix',
            name='step_id_flow',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
