# Generated by Django 4.2.7 on 2025-04-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0008_workflow_matrix_step_id_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_details',
            name='increment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
