# Generated by Django 4.2.7 on 2025-04-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0010_remove_workflow_details_increment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_details',
            name='increment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
