# Generated by Django 4.2.7 on 2025-04-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0012_history_workflow_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_workflow_details',
            name='operator',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
