# Generated by Django 4.2.7 on 2025-04-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0013_history_workflow_details_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_details',
            name='operator',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
