# Generated by Django 4.2.7 on 2025-04-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0014_workflow_details_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_workflow_details',
            name='form_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow_details',
            name='form_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
