# Generated by Django 4.2.7 on 2025-05-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0015_history_workflow_details_form_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_workflow_details',
            name='sent_back',
            field=models.TextField(blank=True, null=True),
        ),
    ]
