# Generated by Django 4.2.7 on 2025-05-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0016_history_workflow_details_sent_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_matrix',
            name='status_color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
