# Generated by Django 4.2.7 on 2025-05-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0017_workflow_matrix_status_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_details',
            name='file_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
