# Generated by Django 4.2.7 on 2025-05-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0020_rename_form_data_id_referenceformstatus_form_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceformstatus',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
