# Generated by Django 4.2.7 on 2025-05-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0021_alter_referenceformstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceformstatus',
            name='old_form_data',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
