# Generated by Django 4.2.7 on 2025-05-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0018_workflow_details_file_number'),
        ('Workflow', '0022_referenceformstatus_old_form_data'),
    ]

    operations = [
    ]
