# Generated by Django 4.2.7 on 2025-07-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0023_merge_20250514_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_matrix',
            name='wf_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
