# Generated by Django 5.0.9 on 2025-07-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumaster',
            name='badge',
            field=models.TextField(blank=True, null=True),
        ),
    ]
